scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets: ["otel-collector:8889"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
